name: Build

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: example-application

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: example-application
          toolchains: arm-zephyr-eabi
      - name: Build firmware
        working-directory: example-application
        shell: bash
        run: |
          west build -b b_l4s5i_iot01a app
      - name: Upload sample_application artifacts
        uses: actions/upload-artifact@v4.6.1
        with:
          name: zephyr-sample_application
          path: example-application/app/build/zephyr/zephyr.*
